### PR TITLE
Rattanak develop

### PR DESCRIPTION
**Pull request by rattanakchea**

### CODE REVIEW

**Comment by seanchung8** [comment]
Rattanak,
Please merge your changes. I am busy doing other cards.

Thanks,

Sean

**Comment by seanchung8** [comment]
Rattanak,
I see the new field in the RegisterActivity for the zip code, but I did not see any changes in the java code. Did you update the java code?

Please let me know.

Thanks,

Sean

**Comment by rattanakchea** [comment]
Yes I made some changes too in the Java file as in this commit
https://github.com/MobileApps-Cascadia/BOOKMARKed/commit/cab7b74869a1ec8b81dae71be3cd95b2b14819e5

and the RegisterActivity.java is
https://github.com/MobileApps-Cascadia/BOOKMARKed/blob/cab7b74869a1ec8b81dae71be3cd95b2b14819e5/app/src/main/java/edu/cascadia/bookmarked/RegisterActivity.java

When I tried to merge, it say already up to date. not sure how to do it properly. Help.

**Comment by seanchung8** [comment]
Ok. I will try to merge it then,

Sean

**Comment by rattanakchea** [comment]
Thanks a lot.

On Fri, Nov 13, 2015 at 11:18 PM, seanchung8 notifications@github.com
wrote:

> Ok. I will try to merge it then,
> 
> Sean
> 
> > On Nov 13, 2015, at 11:10 PM, Rattanak Chea notifications@github.com
> > wrote:
> > 
> > Yes I made some changes too in the Java file as in here
> > cab7b74 <
> > https://github.com/MobileApps-Cascadia/BOOKMARKed/commit/cab7b74869a1ec8b81dae71be3cd95b2b14819e5
> > 
> > https://github.com/MobileApps-Cascadia/BOOKMARKed/blob/cab7b74869a1ec8b81dae71be3cd95b2b14819e5/app/src/main/java/edu/cascadia/bookmarked/RegisterActivity.java
> > <
> > https://github.com/MobileApps-Cascadia/BOOKMARKed/blob/cab7b74869a1ec8b81dae71be3cd95b2b14819e5/app/src/main/java/edu/cascadia/bookmarked/RegisterActivity.java
> > 
> > When I tried to merge, it say already up to date. not sure how to do it
> > properly. Help.
> > 
> > —
> > Reply to this email directly or view it on GitHub <
> > https://github.com/MobileApps-Cascadia/BOOKMARKed/pull/22#issuecomment-156658820
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MobileApps-Cascadia/BOOKMARKed/pull/22#issuecomment-156661029
> .

## 

Regards,
Rattanak Chea
Computer Science Undergraduate
Phone: 206 753-9753

**Comment by seanchung8** [comment]
Is the  fetchZipCode method has any use at all or can I just skip it?

**Comment by rattanakchea** [comment]
It does not do anything now. Yes u can.

**Pull request merged**
