### PR TITLE
Reorganized menu items in order to stream line the application flow.

### PR DESCRIPTION
**Pull request by seanchung8**
All,
Please try this branch and let me know if the menu re-organization makes sense.

Thanks,

Sean

### CODE REVIEW

**Comment by rattanakchea** [comment]
Yes I like this menu. It is more clean and easy to navigate.

**Comment by seanchung8** [comment]
Pawanjit & Debra,
Did you have a chance to take a look? If so, do you have any input?

Thanks,

Sean

**Comment by Cascadia-PawanjitNayyar** [comment]
Hello Sean,

I missed this email.  I will test it and let you know

**Comment by ghost** [comment]
Sean,

I like it too.

--Debra

---

On Thu, 12/3/15, seanchung8 notifications@github.com wrote:

 Subject: Re: [BOOKMARKed] Reorganized menu items in order to stream line the application flow. (#46)
 To: "MobileApps-Cascadia/BOOKMARKed" BOOKMARKed@noreply.github.com
 Date: Thursday, December 3, 2015, 11:59 PM

 Pawanjit & Debra,
 Did you have a chance to take a look? If so, do you have any
 input?

 Thanks,

 Sean

> On Dec 3, 2015, at 4:17 PM, Rattanak Chea notifications@github.com
>  wrote:
> 
> Yes I like this menu. It is more clean and easy to
>  navigate.
> 
> —
> Reply to this email directly or view it on GitHub
>  https://github.com/MobileApps-Cascadia/BOOKMARKed/pull/46#issuecomment-161831434.

---

**Comment by Cascadia-PawanjitNayyar** [comment]
Excellent work Sean. I like it how the menu items change depending on your login status.

**Pull request merged**
