### PR TITLE
add bookImage to sale/wanted view, modify bookAdapter and BookItem class

### PR DESCRIPTION
**Pull request by rattanakchea**
- also adjust book_list_item_layout_row3.xml to make book image scale proportionally.

### CODE REVIEW

**Comment by seanchung8** [comment]
Thanks Rattanak.

All,
We would not taking any picture for the book wanted. Should we consider removing the image view from the list view for the book wanted?

Sean

**Comment by rattanakchea** [comment]
Since BookWanted and BookForSale share the same activity/Fragment, i.e
BookDetail.
We need programmatically remove imageView from BookWanted.

Not sure where to hide bookImage view at this point.

I tried hiding it in BookWantedActivity, but it didn't work.

imv.setVisibility(View.GONE);

On Tue, Dec 8, 2015 at 8:30 AM, seanchung8 notifications@github.com wrote:

> Thanks Rattanak.
> 
> All,
> We would not taking any picture for the book wanted. Should we consider
> removing the image view from the list view for the book wanted?
> 
> Sean
> 
> > On Dec 7, 2015, at 10:02 PM, Rattanak Chea notifications@github.com
> > wrote:
> > 
> > Merged #49 https://github.com/MobileApps-Cascadia/BOOKMARKed/pull/49.
> > 
> > —
> > Reply to this email directly or view it on GitHub <
> > https://github.com/MobileApps-Cascadia/BOOKMARKed/pull/49#event-485279455
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MobileApps-Cascadia/BOOKMARKed/pull/49#issuecomment-162936856
> .

## 

Regards,
Rattanak Chea
Computer Science Undergraduate
Phone: 206 753-9753

**Comment by seanchung8** [comment]
I can take a quick look at hiding the image view. Thanks for getting other things done. It’s looking better everyday :)

Sean

**Comment by Cascadia-PawanjitNayyar** [comment]
Yes please.

**Pull request merged**
