### PR TITLE
Post a book detail

### PR DESCRIPTION
**Pull request by seanchung8**
Team,
Here is my latest commit for BOOKMARKed. I have implemented post a book for sale and it saves the data to the backend. I also implemented the barcode scanning capability to capture the isbn number. Please review when you have a chance.

Thanks,

Sean

### CODE REVIEW

**Comment by Cascadia-PawanjitNayyar** [comment]
hey Sean,

I can't seem to find the .xml file.

**Comment by seanchung8** [comment]
Which one? All the resource files?

Let me know.

Sean

**Comment by seanchung8** [comment]
They should be there. I just checked at github. See screen shot.

Sean

**Comment by Cascadia-PawanjitNayyar** [comment]
I am looking for the layout file which is the .xml file.

**Comment by Cascadia-PawanjitNayyar** [comment]
I see the java file but not the .xml file

**Comment by seanchung8** [comment]
Pawanjit,
Try again. They should be there now. I just take a screen shot.

**Comment by Cascadia-PawanjitNayyar** [comment]
I see it now Sean. Thanks!

**Comment by rattanakchea** [comment]
Thanks Sean for pulling this together.

I made a pull request too, I made some change to setting_activity and
fragment.
Inevitably we are making changes to the same files. I am curious how we can
manage to merge branches and resolve any code conflicts.
That should be part of our group conversation tomorrow.

Rattanak

On Thu, Nov 5, 2015 at 10:30 PM, Cascadia-PawanjitNayyar <
notifications@github.com> wrote:

> I see it now Sean. Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MobileApps-Cascadia/BOOKMARKed/pull/16#issuecomment-154322288
> .

## 

Regards,
Rattanak Chea
Computer Science Undergraduate
Phone: 206 753-9753

**Pull request closed without merging**
