### PR TITLE
Add share intent in 

### PR DESCRIPTION
**Pull request by rattanakchea**
Add shareIntent in BookDetailActivity to share specific book to FB, Google+, email.

Please test it to see if it is working properly on your side.

### CODE REVIEW

**Comment by rattanakchea** [comment]
screenshot_2015-12-08-11-11-58 1
screenshot_2015-12-08-11-12-06 1
screenshot_2015-12-08-11-12-17 1

**Comment by rattanakchea** [comment]
screenshot_2015-12-08-11-11-58
screenshot_2015-12-08-11-12-06
screenshot_2015-12-08-11-12-17

**Comment by seanchung8** [comment]
I just got your share branch, and ran the app briefly. It’s looking good.  I have a few suggestions:
1. could you also apply to book wanted to buy
2. when the app prompt the email, could you pre-populate some fields like subject such as ‘<title> book for sale” or ‘<title> book wanted’
3. also notify where people can view the book (i.e. via BookmarkEd application) and may be put the link to the google play where user can download the app.

Thanks,

Sean

**Comment by Cascadia-PawanjitNayyar** [comment]
Hey Rattanak,

I can't seem to find the branch.

**Comment by seanchung8** [comment]
Should be there. I got it ok.

Sean

**Comment by Cascadia-PawanjitNayyar** [comment]
I found it. Thanks!

**Pull request closed without merging**
