### PR TITLE
Bar code book wanted

### PR DESCRIPTION
**Pull request by rattanakchea**
fix barcode scanner for bookwanted
Note: need to update code in My Posting activity in order for edit/delete bookwanted to work.

### CODE REVIEW

**Comment by seanchung8** [comment]
Rattanak,
You have a note:

> Note: need to update code in My Posting activity in order for edit/delete bookwanted to work.
> 
> Is the edit/delete book wanted not working on this branch? Could you please compare the edit/delete behavior in the main develop branch? Please let me know if the behaviors are different between  the branches.

In the mean time, please hold the merge.

Thanks,

Sean

**Comment by rattanakchea** [comment]
The edit and delete is not working for book wanted when opening the wanted book from My Posting activity.
I think it is only because I had not updated the URI to bookwanted api. I will do more testing tomorrow.

I told Pawanjit not to merge as well.

**Comment by seanchung8** [comment]
Let me re-phrase my question. If you build the current develop (main) branch (not the barcodebookwanted), are the edit and delete work for book wanted?

If they are not working, please let me know.

Thanks,

Sean

**Comment by rattanakchea** [comment]
I built the BarcodeBookWanted, did not touch the develop.

The delete actually works fine. The edit not working, It displays a toast "Error occurred" when trying to save edited.

The edit / delete are supposed to be working on Develop, right?

**Comment by Cascadia-PawanjitNayyar** [comment]
I added code to the activityresults method.

**Comment by Cascadia-PawanjitNayyar** [comment]
I made these changes in the barcodebookwanted branch. I didn't touch any
other part of the code in this branch.

**Pull request closed without merging**
